config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants
  resources :shops
  resources :cafes
  resources :shops do
    collection do
      get 'search'
    end
  end
  resources :cafes do
    collection do
      get 'search'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cafes_controller.rb
require 'net/http'
require 'uri'
require 'json'

class CafesController < ApplicationController

  def index
    @prefectures = Prefecture.all
    service = HotpepperService.new('YOUR API KEY')
    # binding.pry
  end

  def show
    # APIエンドポイントのURIを決定
    uri = URI.parse('http://webservice.recruit.co.jp/hotpepper/gourmet/v1/')
    uri.query = URI.encode_www_form({
      key: 'YOUR API KEY',
      lat: 35.4622429,
      lng: 133.0664864,
      range: 3,
      genre: 'G014', # カフェを選択
      keyword: params[:keyword],
      large_area: params[:large_area],
      count: 20,
      format: 'json'
    })

    request = Net::HTTP::Get.new(uri.request_uri)
    response = Net::HTTP.start(uri.host, uri.port) do |http|
      http.request(request)
    end

    # json形式のデータをハッシュに変換
    json = JSON.parse(response.body)
    @shops = json["results"]["shop"]
    # pryによるデバッグ
    # binding.pry
    render :search_result

  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    #リクエスト送信
    url = URI.parse("http://webservice.recruit.co.jp/hotpepper/gourmet/v1")
    url.query = [
      "id=" + "J001160647",
      "name" + "いいとこ鶏 池袋本店",
      "key=" + "64021912cf2b3b35"
    ].join("&")

    req = Net::HTTP::Get.new(url.request_uri)

    ret = Net::HTTP::start(url.host, url.port, use_ssl: true) do |http|
      http.request(req)
    end

    
    
    #nokogiri::xml::document生成
    xml = Nokogiri::XML(ret.body)
    #名前空間の定義
    namespace = {
      "results" => "http://webservice.recruit.co.jp/HotPepper" # ここのURLはなんぞ？
    }
    @ydf = xml.xpath('//results:api_version', namespace).text
    @result = ydf.xpath("results:id/results:name", namespace).text.first

  end
end

app/controllers/shops_controller.rb
require 'net/http'
require 'uri'

class ShopsController < ApplicationController
  def index
    service = HotpepperService.new('YOUR API KEY')
  end

  def show
    # APIエンドポイントのURIを決定
    uri = URI.parse('http://webservice.recruit.co.jp/hotpepper/gourmet/v1/')
    uri.query = URI.encode_www_form({
      key: 'YOUR API KEY',
      keyword: params[:keyword],
      # large_area: params[:large_area],
      # range: params[:range],
      # lat: params[:lat],
      # lon: params[:lon],
      # id: params[:id],
      format: 'xml'
    })

    # response = Net::HTTP.get_response(uri)
    # response = Net::HTTP::Get.new(uri.request_uri)
    request = Net::HTTP::Get.new(uri.request_uri)
    response = Net::HTTP.start(uri.host, uri.port) do |http|
      http.request(request)
    end

    #nokogiri::xml::document生成
    xml = Nokogiri::XML(response.body)

    # pryによるデバッグ
    # binding.pry


    # 名前空間の定義 => 今回不要
    # namespace = {
    #   "results" => "http://webservice.recruit.co.jp/HotPepper/"
    # }
    # results = xml.xpath('//results', namespace)

    # ログデバッグ
    # logger.debug("***************#{Nokogiri::XML(results).inspect}")


    # @shops = Nokogiri::XML(results.text)
    @shops = xml.xpath('/').children[0].children
    @image_url = []
    @shops[2].text.to_i.times do |i|
      @image_url.push(@shops[i+4].children[2].text)
    end

    # -- @shopsのindex --
    # 0 version
    # 1 result_available
    # 2 results_returned
    # 3 results_start
    # 4以降は店舗情報
    #
    # -- @shops.children[i] --
    # 0：id
    # 1：name
    # 2：logo_image
    # 3：name_kana
    # 4：address
    # 5：station_name
    # 6：ktai_coupon
    # 7：large_service_area
    # 8：service_area
    # 9：large_area
    # 10：middle_area
    # 11：small_area
    # 12：lat
    # 13：lng
    # 14：genre
    # 15：sub_genre    
    # 16：budget    
    # 17：catch    
    # 18：capacity    
    # 19：access    
    # 20：mobile_access    
    # 21：urls    
    # 22：photo    
    # 23：open    
    # 24：close    
    # 25：party_capacity    
    # 26：other_memo    
    # 27：shop_detail_memo    
    # 28：budget_memo    
    # 29：wedding    
    # 30：course    
    # 31：free_drink    
    # 32：free_food    
    # 33：private_room    
    # 34：horigotatsu    
    # 35：tatami    
    # 36：card    
    # 37：non_smoking    
    # 38：charter    
    # 39：parking    
    # 40：barrier_free    
    # 41：show    
    # 42：karaoke    
    # 43：band    
    # 44：tv    
    # 45：lunch    
    # 46：midnight    
    # 47：english    
    # 48：pet    
    # 49：child    
    # 50：wifi    
    # 51：coupon_urls

    # binding.pry


    render :search_result

  end

  # def show
  #   service = HotpepperService.new('YOUR API KEY')
  #   @shops = service.search_shops(params[:keyword])['results']['shop']
  #   p @shops
  #   render :search_result
  # end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cafes/index.html.erb
<h1 class="display-4 text-primary" >cafes#index</h1>

<%= form_with url: search_cafes_path, method: :get, local: true do |f| %>
  <div class='form-group'>
    <%= f.label :keyword, "キーワード", class: 'display-8 text-primary' %>
    <%= f.text_field :keyword, class: 'form-control' %>
    <div class="accordions">
      <details class="accordion-001">
        <summary>関東</summary>
        <% @prefectures[0..6].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
      <details class="accordion-001">
        <summary>関西</summary>
        <% @prefectures[7..12].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
      <details class="accordion-001">
        <summary>東海</summary>
        <% @prefectures[13..16].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
      <details class="accordion-001">
        <summary>北海道</summary>
        <label><%= @prefectures[17].name %><%= f.radio_button :large_area, @prefectures[17].code %></label>
      </details>
      <details class="accordion-001">
        <summary>東北</summary>
        <% @prefectures[18..23].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
      <details class="accordion-001">
        <summary>北陸・甲信越</summary>
        <% @prefectures[24..29].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
      <details class="accordion-001">
        <summary>中国</summary>
        <% @prefectures[30..34].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
      <details class="accordion-001">
        <summary>四国</summary>
        <% @prefectures[35..39].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
      <details class="accordion-001">
        <summary>九州・沖縄</summary>
        <% @prefectures[40..47].each do |prefecture| %>
          <label><%= prefecture.name %><%= f.radio_button :large_area, prefecture.code %></label>
        <% end %>
      </details>
    </div>
    <%= f.submit "検索", class: 'primary' %>
  </div>

<% end %>

app/views/cafes/search_result.html.erb
<h1 class="display-4 text-primary" >cafes#index</h1>
<% if @shops.present? %>
  <% @shops.each do |shop| %>
    <h2>店名：<%= shop["name"] %></h2>
    <p>住所：<%= shop["address"] %></p>
    <p>画像：<%= image_tag(shop["photo"]["pc"]["m"]) %></p>
    <p>店舗URL：<%= link_to "店舗情報へ", shop["urls"]["pc"] %></p>
    <p>店舗ロゴ：<%= image_tag(shop["logo_image"]) %></p>
  <% end %>
<% else %>
  <h1>あぁ、、その検索結果は見つかりませんでした。</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotPepperApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="container">
    <%= yield %>
    <a href="http://webservice.recruit.co.jp/"><img src="http://webservice.recruit.co.jp/banner/hotpepper-s.gif" alt="ホットペッパーグルメ Webサービス" width="135" height="17" border="0" title="ホットペッパーグルメ Webサービス"></a>
  </body>
</html>

app/views/restaurants/index.html.erb
<%= @ydf %>

app/views/shops/index.html.erb
<h1 class="display-4 text-primary" >shops#index</h1>

<%= form_with url: search_shops_path, method: :get, local: true do |f| %>
  <div class='form-group'>
    <%= f.text_field :keyword, class: 'form-control' %>
    <%#= f.text_field :large_area, class: 'form-control' %>
    <%= f.submit "検索", class: 'primary' %>
  </div>

<% end %>

app/views/shops/search_result.html.erb
<% @shops[2].text.to_i.times do |i| %>
  <h2>店名：<%= @shops[i+4].children[1].text %></h2>
  <p>住所：<%= @shops[i+4].children[4].text %></p>
  <p>画像：<%= image_tag(@shops[i+4].children[22].text.scan(/https?:\/\/\S+?\.jpg/)[1]) %></p>
  <p>店舗URL：<%= link_to "店舗情報へ", @shops[i+4].children[21].text %></p>
  <p>店舗ロゴ：<%= image_tag(@image_url[i]) %></p>
<% end %>

<p><%= @shops[2].text %>件表示</p>

<% 52.times do |i| %>
  <p><%= "#{i}：" + @shops[5].children[i].name %></p>
<% end %>